### ISSUE TITLE
Post Detail onResume()

### ISSUE THREAD

**Issue by ParkYoungJin0303** [DsmMarket/Android#61]
PostDetail에서 onResume 함수가 호출되면 자신이 쓴 글이지만 채팅으로 거래하기가 뜹니다

**Comment by ParkYoungJin0303** [comment]
다른사람과 채팅을 할 때도
토스트 - 서버에 문제가 발생했습니다

**Comment by kimdohun0104** [comment]
문제는 해결했지만 해결 방식이 느낌없습니다.
클래스에 isMe라는 변수를 사용하여 onResume에서 true라면 View.GONE해주는 방식입니다.
다른 방편이 나올 때 까지 임시로 사용할 예정입니다. 
일단 이슈는 닫을건데 후에 다른 아이디어가 있다면 다시 오픈해주세요
