### ISSUE TITLE
댓글 신고

### ISSUE THREAD

**Issue by ParkYoungJin0303** [DsmMarket/Android#62]
자신이 남긴 댓글을 신고할 수 있습니다

**Comment by kimdohun0104** [comment]
이 부분은 서버개발자에게 전달하도록 하겠습니다.
서버의 변경과 클라이언트 모두 변경되었을 때 이슈 닫을게요

**Comment by kimdohun0104** [comment]
서버 개발자와 상의 후 변경했습니다.
