### ISSUE TITLE
채팅

### ISSUE THREAD

**Issue by ParkYoungJin0303** [DsmMarket/Android#65]
날짜가 바뀌고 채팅을 할 시,
2019-XX-XX가 최근 단 댓글 이전에 달리는게 아닌
아이템의 맨 처음에 달립니다

**Comment by ParkYoungJin0303** [comment]
다시 들어가면 정상적으로 보임

**Comment by kimdohun0104** [comment]
인덱스가 조금 헷갈렸던 모양입니다.
날짜를 추가할 때 0번 인덱스에 추가하도록 하여 해결했습니다
