### ISSUE TITLE
Hey hey, Do you know dark theme issue In your App?

### ISSUE THREAD

**Issue by ParkYoungJin0303** [DsmMarket/Android#67]
한국어로 설정된 상태에서
인앱 실행 중 테마 변경을 하면
언어가 영어로 바뀝니다.

**Comment by kimdohun0104** [comment]
build.gradle에서 resConfigs 설정을 삭제하니 문제가 해결되었습니다.
그런데 다크테마로 변경한 뒤 BottomNavigationView가 동작하지 않는 오류는 잡지 못했습니다.
(진짜 답이 없는건가...)
새로 이슈 파겠습니다.
