### ISSUE TITLE
아이템이 없을 때

### ISSUE THREAD

**Issue by ParkYoungJin0303** [DsmMarket/Android#73]
Purchase, Rent, Chat 등의  아이템이 존재하지 않을경우
x가 없습니다.  라는 문구를 보여주어야
유저가 아이템이 없어서 안뜬다고 알 것 같습니다.

(특히 채팅 같은 경우, 누구나 처음에 채팅이 없으므로 어색함을 보여줌)

**Comment by kimdohun0104** [comment]
완전 우아하게 해결했습니다.
아래의 커밋 기록을 확인하세요.
[클릭해서 확인하세요](https://github.com/DsmMarket/Android/commit/ef4c1e087c5166c53533987efcaf26645786e77f)
